/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-error-container": "#ffdad6",
        "on-primary": "#263046",
        "inverse-on-surface": "#2f312e",
        "tertiary-container": "#002842",
        "outline": "#8f9097",
        "tertiary-fixed-dim": "#94ccff",
        "on-secondary-fixed-variant": "#2f4865",
        "on-primary-fixed": "#101b30",
        "inverse-primary": "#545e76",
        "surface-variant": "#333533",
        "on-tertiary-fixed-variant": "#004b74",
        "outline-variant": "#45474d",
        "secondary-fixed": "#d1e4ff",
        "on-secondary": "#17324d",
        "on-surface-variant": "#c5c6cd",
        "primary": "#bbc6e2",
        "secondary": "#afc9ea",
        "on-secondary-fixed": "#001d36",
        "on-primary-fixed-variant": "#3c475d",
        "surface-container-lowest": "#0c0f0d",
        "surface-tint": "#bbc6e2",
        "surface-container-low": "#1a1c1a",
        "on-primary-container": "#828da7",
        "secondary-fixed-dim": "#afc9ea",
        "surface": "#111412",
        "error": "#ffb4ab",
        "inverse-surface": "#e2e3df",
        "tertiary": "#94ccff",
        "surface-container": "#1e201e",
        "surface-bright": "#373a37",
        "on-tertiary-container": "#3a93d4",
        "secondary-container": "#2f4865",
        "surface-container-high": "#282b28",
        "on-background": "#e2e3df",
        "primary-fixed": "#d9e2ff",
        "on-tertiary": "#003251",
        "tertiary-fixed": "#cee5ff",
        "outline-variant-2": "#45474d",
        "error-container": "#93000a",
        "on-surface": "#e2e3df",
        "primary-container": "#3c475d",
        "primary-fixed-dim": "#bbc6e2",
        "surface-dim": "#111412",
        "on-secondary-container": "#afc9ea",
        "on-error": "#690005",
        "surface-container-highest": "#333533"
      }
    },
  },
  plugins: [],
}
